### ISSUE TITLE
Pre-release issues

### ISSUE THREAD

**Issue by mikee47** [mikee47/ConfigDB#1]
Items to fix before considering an initial release:

* [x] Validate schema before parsing
* [x] Add stream parsers for sending/receiving database content, e.g. to/from web clients
* [x] Implement default value support. Thus, a default initial configuration can be created
* [x] Consider how store load failures are handled. For example, file corruption or partial reads can lead to data inconsistencies. Application can choose to use partial data, increase available RAM for loading, revert to defaults, etc.
* [x] Implement range checking support
* [x] Enable custom value types. ~~For example, can map *string* object with *ip4* format to `IpAddress`.~~ use `ctype` annotation.
* [x] Implement floating point number support. The *number* type can be used for this although according to the spec. it can also contain integers.
* [x] Generate `struct` for each `Object` which applications can use to persist contents in code. Provide methods to read/write these structures.
* [x] Add format parameter for serialisation (compact or pretty JSON)
* [x] Implement `Property` class abstraction to manage key/value string pair with an associated type enumeration.
* [x] Support lookup by JSONPath to return corresponding `Object`~~or `Property`~~. We need this so web clients can request specific items.
* [x] Support iterating `Object` child objects and properties.
* [x] Consider whether ArduinoJson is still required. We may not need all the optimisations and features it offers. Removed in favour of custom storage pools.
* [x] Write test application
* [x] Add notes on annotating schema (title, description) and ways to generate documentation (#4)
* [x] Review memory usage
* [x] ~~Check for reserved identifiers (e.g. `int`, `float`) in code generator~~ Not bothering.
* [x] Add array iterator support.
* [x] Handle array `default` value or generate warning if it remains unsupported.
* [x] How to reset property value to default? We can do this for entire arrays and objects using `clear` or `resetToDefaults`. The defaults are available in the defined `defaultData` structures but these are generally not for application use as the types don't always concur with the API. Could add `resetXXX()` methods?
* [x] Support definitions in external files.

**Comment by mikee47** [comment]
Regarding *range checking support* the (optional) `minimum` and `maximum` values in the schema are only used to determine the storage type for an integer, but there is the presumption that the database will validate property values in some way.

I'm inclined to do this by generating code for the **setXXX** methods, and have it clip the value to the given range.

Alternatively, invalid values could be silently rejected but that's probably less useful.

The downside of this approach is that streaming imports wouldn't get validated. That would require the generated type information to include the range and code would need to deal with that for all supported types.

My feeling is that the web client should be handling validation using the schema anyway, so this shouldn't be such a big issue.

@pljakobs Any thoughts?

**Comment by mikee47** [comment]
Also *lookup by JSONPath* I don't think we've yet encounted a situation where this is required so I'm thinking leave that until the need arises.

**Comment by pljakobs** [comment]
sorry, just saw that I owe you an answer here still.
If using the C++ functions, I believe clipping max/min should be ok, I wonder if that also shoudl be an error condition (right now, the setXXX functions are void, right?)
Through the streaming "interface" (I do think of it mostly as my json over http API) I guess it's more difficult. But: if we observe clipping, we could possibly deal with it in the context of change tracking (or callbacks, as discussed elsewhere. 
If we have a status bitfield that reports on the database, we may have more than one bit per property, such as "changed in last operation", "overflow", "underflow", "bad format" (when non-numeric characters are given for a numeric field) etc.
An implementation that cares could then, after an import, verify this (albeit, thinking about it, this should probably work the other way round, such that the application doesn't have to iterate over every property but can ennumerate a list of changes / errors) 
This way, if the developer wants, they could create, for example, a json response that provides the error  back to the user or sanitize local values if needed.

**Comment by mikee47** [comment]
Seems to be reasonably useable so going for a `1.0.0` release so we can add it to `Sming`.
