### ISSUE TITLE
Database sharing

### ISSUE THREAD

**Issue by mikee47** [mikee47/ConfigDB#12]
So with asynhronous streaming we have the issue of local/remote update conflicts.

## The problem

Remote client is reading database via stream. This opens each store in turn and sends the content out. During this time, a local application (or another web client) may access the database. If everyone is just reading the database, then there should be no issue.

However, only one instance of any store is loaded into RAM at a time and that instances is shared amongst all users.
If a change is made, then that change would be immediately affect all other readers, even before `commit` is called.

Possible effects, best to worst-case:

- No problem. We get lucky and store is updated before anyone else notices, so data is consistent.
- Data is inconsistent. Store is updated during reading and client gets new value before it's committed. Value in a data object are out of sync.
- Deleted array item is accessed causing assertion failure

If a remote client is updating database via stream then the likelihood of a problem is increased as streaming is (relatively) long-running.

## Solution

To use classic database parlance, we need to implement table-level locking (table === store) to prevent multiple conflicting updates.

A 'mode' flag would be required to indicate intent when opening a store:

```
BasicConfig::Root::Security sec(database, ConfigDB::Mode::ReadWrite);
if(sec) {
    sec.setApiSecured(true);
    sec.commit();
} else {
    // Store is locked!
}
```

If the store is already opened for writing then the `sec` object will be invalid (`if (sec)` fails) and any attempt to read or write would cause a hard assertion failure.

Passing `ConfigDB::Mode::ReadOnly` would indicate we don't intend to write and would always succeed. We could generate `const` object versions:

```
BasicConfig::Root::SecurityConst sec(database);
sec.setApiSecured(true);
sec.commit();
```

This is clearly wrong code and the compiler would catch it since `const` classes won't have any `set` or `commit` methods.

Multiple readers share an instance of a store, but a writer always gets its own copy.
When changes are committed, a new writer will get the revised data but existing readers will not. (Updating the store in-situ is complex and risky.)

We also have a choice here: do new readers use the existing (stale) reader store, or open a new one?

A mechanism would also be necessary to propagate sharing violation errors back to a web client so it can retry.
This is tricky since the HTTP response header would have already been sent, so may need a second request to check the status of the update.

**Comment by pljakobs** [comment]
hmm.. I see the point, and I think it would be good to have at least store level consistency (like, when you enable password security, it doesn't make sense when there's no password and that would lead to a potentially difficult result).
But also, I'm not sure i want the user to deal with the complexity of consistency management.
Taking my example: currently, the configuraition is held in a global struct and thus any code anywhere can access it. There is a (I guess small) window that the global struct may not be consistent (iE for the time from when the config update starts breaking down a json update to when it finishes, but that would be a much shorter time than the the streaming to database would take.

How about a flag to signal tolerance by a reader? it could indicate "current value" or "consistent value" with the latter perhaps waiting for a pending update operation. 

Config updates don't happen overly often, so the short delays that might come through them should be tolerable. 
I guess I'm thinking along the lines of nfs hard and soft mounts but hopefully with a fail timeout if the lock is never cleared.

**Comment by mikee47** [comment]
I agree that consistency should be taken care of without hassle. Let's have an example:

```
BasicConfig::Root::Network::ApConst ap(database);
String ssid = ap.getSsid();
String password = ap.getPassword();
```

We want the retrieved values for `ssid` and `password` to **always** be consistent, and as up-to-date as possible.

The key required for applications here is that they **never** hang on to these objects. So they are strictly locally scoped, never copied to the heap or persisted. Things like `new BasicConfig::Root::Network::ApConst` are strictly forbidden - if possible, I'll make sure the compiler rejects that sort of thing.

Having said that, this is exactly the behaviour of our streaming reader/writer classes! And it's absolutely necessary so it can do its job.

Possible scenarios:

- Web client starts update
    - Json::WriteStream class is created
    - Each store is updated in turn
        - When opened, a new copy is loaded from storage
        - At commit, copy is written back to storage (atomically)

During this time, the above example code gets run by the application.

- Root store is opened for writing
    - New Store instance is loaded into RAM
- Root store isn't opened for reading or writing
    - New Store instance is loaded into RAM
- Second web client starts a streaming database read
    - Root store is opened read-only
        - Existing store instance is shared with client above
    - Root store is opened for writing
        - New Store instance is loaded into RAM

I think that covers everything?

**Comment by pljakobs** [comment]
so ideally, what you suggest is that all store use should be scoped as small as possible, not to have stores dangling throughout runtime? 

taking your example above:

```
{
   BasicConfig::Root::Network::ApConst ap(database);
   String ssid = ap.getSsid();
   String password = ap.getPassword();
}
if(WifiAccessPoint.config(ssid, password, AUTH_WPA2_PSK))
           WifiAccessPoint.enable(true);
```
now, configuring the ap is not a very likely scenario for a concurrent access, so this should always work (famous last words).

Since you are suggesting that a new instance would be loaded from storage and we assume that a store is only written to storage once it is fully updated (also in stream mode) - I don't see an issue with consistency. Any store I open would always reflect the state at time of opening but that should (proper coding provided) be consistent. 
So I think where I might disagree with what you said above is the 2nd client read-write case: sharing it with the other client saves memory and gets us up to the second values, it does so by potentially foregoing consistency. Loading it from storage would turn this around - at the price of memory. I believe that I would prefer consistency over up-to-the-second.

Am I misunderstanding something?

**Comment by mikee47** [comment]
> so ideally, what you suggest is that all store use should be scoped as small as possible, not to have stores dangling throughout runtime?

Yes, exactly so. Open the store, read the data, close the store. This is fine though:

```
{
   BasicConfig::Root::Network::ApConst ap(database);
   if(WifiAccessPoint.config(ap.getSsid(), ap.getPassword(), AUTH_WPA2_PSK)) {
           WifiAccessPoint.enable(true);
   }
}
```

What would be bad though is if the call to `WifiAccessPoint.enable` (or whatever function gets called) ends up servicing the LWIP network stack directly. That sort of thing is specifically avoided in Sming by using the task queue, so the stack is unwound fully before calling another chunk of code. Hence we should not need to worry about that sort of thing.

> So I think where I might disagree with what you said above is the 2nd client read-write case: sharing it with the other client saves memory and gets us up to the second values, it does so by potentially foregoing consistency. Loading it from storage would turn this around - at the price of memory. I believe that I would prefer consistency over up-to-the-second.

*potentially foregoing consistency* no, that's not my intention.

Here's my thoughts about how this could be implemented. At present, the `Database` keeps **one** `shared_ptr<Store>` just for the most recently accessed store. That gets tidied up via the task queue so pretty much immediately. But it means code like this doesn't have to reload the store for each call:

```
configureAp(BasicConfig::Root::Network::ApConst(database));
configureSecurity(BasicConfig::Root::Network::SecurityConst(database));
```

What we could do is add a second `shared_ptr<Store>` for writing, and for exactly the same reason. Let's call these `readRef` and `writeRef`. We also need a `weak_ptr<Store>` for writers so we can tell if there is a writer in use. We'll call that `writeWeakRef`.

When the `Database` is asked to open a store for writing, it succeeds only if `writeWeakRef.use_count() <= 1`: this enforces the single-writer policy.

When the writer calls `commit`, the `Database` clears `readRef` which ensures that any new readers get the updated store. Existing readers remain unchanged.

I did think for a moment that we could optimise this by setting `readRef = writeRef`, but if the writer does further updates we're in trouble. So let's not do that!

**Comment by mikee47** [comment]
NB. The above example is somewhat contrived. This would be better:

```
BasicConfig::Root::NetworkConst network(database)
configureAp(network.ap);
configureSecurity(network.security);
```

**Comment by mikee47** [comment]
What are your thoughts on having separate `Network` and `NetworkConst` classes?

**Comment by pljakobs** [comment]
> What are your thoughts on having separate `Network` and `NetworkConst` classes?

with const being truly constant? Not sure I understand the question.

**Comment by mikee47** [comment]
The implemention outlined above is a little simplistic since we need to track writes on every store type. Becomes a little more elaborate but the same principle applies.
