### ISSUE TITLE
premature end of document / getObjectArrayDataPtr assert fail

### ISSUE THREAD

**Issue by pljakobs** [mikee47/ConfigDB#14]
building and running the current 'develop' sample, I get the follwoing error on Host arch:

```
14930 parsing 'test/general.json'
0. ARR(0) OBJECT '': Object
  1. OBJ(0) OBJECT 'channels': DATA 1
ObjectArray[]
  1. OBJ(1) OBJECT 'supported_color_models': DATA 1 @ 9fd6f00+2
Array[String]
  1. OBJ(2) PROPERTY 'device_name' @9fd6f00[4:6]: DEFAULT String = "" (0)
DATA 0, STRINGS 
  1. OBJ(3) PROPERTY 'pin_config_url' @9fd6f00[6:8]: DEFAULT String = "https://raw.githubusercontent.com/pljakobs/esp_rgb_webapp2/devel/public/config/pinconfig.json" (0)
DATA 0, STRINGS 
  1. OBJ(4) PROPERTY 'current_pin_config_name' @9fd6f00[8:10]: DEFAULT String = "mrpj" (0)
DATA 0, STRINGS 
  1. OBJ(5) PROPERTY 'buttons_debounce_ms' @9fd6f00[10:12]: UInt16 = 50 (50)
DATA 50, STRINGS 
  1. OBJ(6) PROPERTY 'pin_config' @9fd6f00[12:14]: DEFAULT String = "13,12,14,5,4" (0)
DATA 0, STRINGS 
  1. OBJ(7) PROPERTY 'buttons_config' @9fd6f00[14:16]: DEFAULT String = "" (0)
DATA 0, STRINGS 
Parser returned EndOfDocument
app: /opt/Sming/Sming/Components/ConfigDB/src/Store.cpp:42: void* ConfigDB::Store::getObjectArrayDataPtr(ConfigDB::ArrayId, unsigned int): Assertion `false' failed.

signal_handler: SIGABRT - usually caused by an abort() or assert()
```

what confuses me is, that the parser returnes EOD after "buttons_config" as a lot more stuff comes after that - ist this the static json document size being too small? (honestly not having looked at the new stream parser routines yet).

But apart: once this is functional, I think I can start using it in my firmware package and getting some real-world insight.

**Comment by mikee47** [comment]
Yep, that's not current develop, it's from around 11th August! ArduinoJson is gone and we're using custom dynamic allocation. I need to update documention to cover that.

**Comment by mikee47** [comment]
I've been using pull requests to add this major functionality, so have a read of those to discover what's been going on. I've also added some issues to discuss things which need a bit of thought; it might be worth leaving some of that for later so we can get a release done.

**Comment by mikee47** [comment]
NB. ArduinoJson was removed in a merge commit not a PR. 5bb01eb358febe2214f1deda6a2dc0b942241148

**Comment by mikee47** [comment]
I'm much happier with the shape of this library now. It 'feels' much cleaner than trying to work on top of ArduinoJson. We save a ton of RAM not storing key strings too :-)
