### ISSUE TITLE
build isue

### ISSUE THREAD

**Issue by pljakobs** [mikee47/ConfigDB#35]
not sure what happened, but I'm getting 
```cannot open source file "ConfigDB/Database.h"```
now.
This started late yesterday, but I think before pulling the latest changes to `develop`. I have done `make dist-clean` `make components-clean`, `make ConfigDB-rebuild` and `make configdb-rebuild` but the issue is still there. 
Am I missing something? `/opt/Sming/Sming/Components/ConfigDB` tracks upstream/develop, in `src/include/ConfigDB/` I can see the correct files. I am confused.

**Comment by mikee47** [comment]
Can you include the full output please?

**Comment by pljakobs** [comment]
[output_en.txt](https://github.com/user-attachments/files/17005136/output_en.txt)
It seems that the "cannot open..." errror message is only a message that shows up in the VS-Code build and the true issue is around `None`?

**Comment by mikee47** [comment]
Would you share your schema? Probably requires a fix in dbgen.py

**Comment by pljakobs** [comment]
I currently have two schema files, `app-config.cfgdb` and `app-data.cfgdb`
[app-config.cfgdb.txt](https://github.com/user-attachments/files/17005160/app-config.cfgdb.txt)
[app-data.cfgdb.txt](https://github.com/user-attachments/files/17005161/app-data.cfgdb.txt)

**Comment by mikee47** [comment]
OK, should be fixed in develop.

NB. If you find other problems like this you can always push them to your esp_rgbww_firmware fork.

**Comment by pljakobs** [comment]
ok, this fixed it! Thank you (gosh I wish I could offer my customers a fix time like that ;-) )

> NB. If you find other problems like this you can always push them to your esp_rgbww_firmware fork.

not sure I understand, do you mean the cfgdb files? I am not pushing too many updates to the `feature/ConfigDB` branch as I am working trough replacing every occurrence of the config struct with the matching ConfigDB call. Will take a bit until this builds.

**Comment by mikee47** [comment]
In your config I note you have an array *default* setting. This is currently ignored for arrays (!) so I should either implement it or generate a warning...

```json
        "supported_color_models":{
            "type": "array",
            "items":{
                "type":"string"
            },
            "default":["RGB", "RGBW", "RGBWW", "RAW"]
        }
```
