### ISSUE TITLE
configdb property definition for alias

### ISSUE THREAD

**Issue by pljakobs** [mikee47/ConfigDB#43]
I believe this might be a strange request but:

while refactoring my app to use ConfigDB, I found some naming inconsistencies in the original code.
As an example, one property was called `transfin_interval` which, I believe, should have been called `trans_fin_interval` since it stands for transition finish interval. There were one or two others where I thought the original naming was inconsistent.

If I was importing this json document manually, as before, I could easily write code that understands that `transfin_interval` and `trans_fin_interval` are the same and provide compatibility. With the stricter definitions of ConfigDB, I can't easily do that and thus it's difficult to maintain compatibility between the old and the new API.

I suggest implementing a mechanism to create an alias similar to this:

```
{
  "trans_fin_interval": {
    "type":"object",
    "properties":{
      "type":"integer"
    }
  },
  "transfin_interval: {
      "type":"alias",
      "of":"{trans_fin_interval}"
  }
}
```
I acknoledge that resolving the object path of the object the alias refers to might be a bit tricky, but I assume that would only have to be done once in compiling the schema.

**Comment by mikee47** [comment]
> I acknoledge that resolving the object path of the object the alias refers to might be a bit tricky, but I assume that would only have to be done once in compiling the schema.

Not really! In the schema we could use a custom `alias` annotiation for this:

```json
{
  "trans_fin_interval": {
    "type":"object",
    "alias": "transfin_interval",
    "properties":{
      "type":"integer"
    }
  }
}
```

This could be a simple string or a string array.

I think generated type information should be more like your suggested JSON, using separate `Alias` PropertyInfo records.

To summarise:

1. Canonical name for property is `trans_fin_interval`, and is what ConfigDB will use when writing
2. Code must be consistent in use, so following underscore-to-camelCase rules we'll get `transFinInterval` for identifiers
3. ConfigDB will need to handle `transfin_interval` when reading JSON

This could actually be pretty useful migrating versions as well, makes it a bit less rigid.

**Comment by pljakobs** [comment]
just realized something: 
making the alias on the API level is one thing, but what will happen if I want to make the new property name the canonical name and the old one the alias (as in your example above) and flash that onto a chip that has a valid database already? The store would have to be migrated to tolerate reading the old name (now the alias) but upon update remove that and write the new canonical name for the property

**Comment by mikee47** [comment]
> just realized something: making the alias on the API level is one thing, ...

Unless I've misunderstood your requirement, there would be no API alias: code would *always* use the canonical property name.

> ... but what will happen if I want to make the new property name the canonical name and the old one the alias (as in your example above) and flash that onto a chip that has a valid database already?

Aliases would be stored separately from regular properties and only referred to during de-serialisation. The alias `transfin_interval` just points to the property definition for `trans_fin_interval`.

> The store would have to be migrated to tolerate reading the old name (now the alias) but upon update remove that and write the new canonical name for the property.

The store could contain `trans_fin_interval` or `transfin_interval` (or both) and both would resolve to the same property. Next time the store is saved it is overwritten and the `transfin_interval` value disappears.

**Comment by pljakobs** [comment]
excellent! This already works and it's great!
I am so impressed with this, I really hope this will become part of Sming proper and be used.
